### PR TITLE
Add midikraken

### PR DESCRIPTION
**Pull request by Windfisch**

### CODE REVIEW

**Review by eldruin — APPROVED** [review]
Wow looks awesome!
Make sure to add it to the [newsletter](https://github.com/rust-embedded/blog) as well :)

bors r+

**Comment by eldruin** [comment]
Ach, this still uses Travis for CI.

**Comment by Windfisch** [comment]
> Wow looks awesome!
> Make sure to add it to the [newsletter](https://github.com/rust-embedded/blog) as well :)

Thanks for your suggestion! How do I do this, the newsletter entries end at `2021-05-07-newsletter-29.md`? Shall I create a new file with the current date, or with a date of `now + N days` (for which value of `N`?)

**Comment by adamgreig** [comment]
That latest entry is still marked `draft`, so a PR to edit that one is fine, we'll update the date when it gets published (hopefully in the next week or two...).

**Comment by Windfisch** [comment]
What is wrong with the CI? Did I make a mistake or is the CI just broken?

**Comment by adamgreig** [comment]
Should be fixed now!

bors retry

**Comment by adamgreig** [comment]
And, it's live http://showcase.rust-embedded.org/

**Comment by Windfisch** [comment]
Yayy, so cool! Thank you :)

**Pull request merged**
