### PR TITLE
[RFC] rotate the list of projects on a daily basis

### PR DESCRIPTION
**Pull request by japaric**
I propose what the title says. The aim is to give all projects equal chance to be
at the top of the site for one day.

Design: rotate the list upwards every day as shown in the diagram below

``` text
          *
A    B    C    D
B -> C -> D -> A
C    A    A    B
          B    C
```

`->` denotes a day transition; `*` indicates that a new project was added that
day that day.

Implementation: we do this in the site generator by rotating the list based on
number of days passed since a known date (e.g. today). Plus we set up a travis
cron job to regenerate the site every day.

Alternatives: do this using JS (we currently use zero JS)

### CODE REVIEW

**Review by therealprof — APPROVED** [review]
SGTM

**Comment by flip111** [comment]
I would prefer for new projects to be in a highlighted section for a week or a month. After that everything fully randomized (server-side not JS)

**Review by andre-richter — APPROVED** [review]

**Review by adamgreig — APPROVED** [review]
SGTM!

**Review by korken89 — APPROVED** [review]

**Comment by japaric** [comment]
This now has enough approvals! (4/4)

bors r+

@flip111 if you would like to propose doing something different please make an RFC issue with more details (e.g. when and how often does "full randomization" happen?)

**Comment by japaric** [comment]
sudo
bors r+

**Pull request merged**
