### PR TITLE
adding my moon lamp project

### PR DESCRIPTION
**Pull request by freiguy1**

### CODE REVIEW

**Review by TeXitoi — APPROVED** [review]
Great project!

**Review by TeXitoi — APPROVED** [review]

**Review by adamgreig — APPROVED** [review]
This looks great, thanks for submitting it!

bors merge

**Comment by adamgreig** [comment]
and, it's live! http://showcase.rust-embedded.org/

**Comment by freiguy1** [comment]
Woot! That was quick, thanks everyone.

**Pull request merged**
