### PR TITLE
Add rusty clock

### PR DESCRIPTION
**Pull request by TeXitoi**
Auto evaluation:

# Hard requirements

> The main logic of the application must be written in Rust.

100% rust (except ASM on the cortex-m and cortex-m-rt crates)

> The source code must be public. Licensing terms are unimportant.

On github, MIT licensed.

# Bonus points

> The project is unlike the projects currently on display.

This one is easy as I'm the first :innocent: 

> The documentation includes instructions on how to build the program, or the firmware can be built with just cargo build.

End of the README.md explain everything (and that's just `cargo build --release` to compile the firmware).

> The repository has a CI setup.

Travis build, run the unit tests and check rust-fmt.

> The application compiles on stable.

Travis tests on stable, beta and nightly.

> The application code is free from unsafe code and all unsafe code has been pushed to libraries that only expose a safe API.

There is one unsafe to clear a timer interrupt (yes, I need to upstream that).

There is also unsafe code in the dependent crate pwm-speaker. I need to upstream an embedded_hal::Pwm impl on stm32f1xx-hal to remove it.

> Code that's not target specific, if any, has unit tests.

There is some light unit tests on the `portable` subcrate (80% of the code) that contains all the code that can be run on amd64.

> Support code, if any, is documented.

I don't understand what is support code.

# Penalties

> The application contains potential soundness issues. For example, using mem::transmute, unchecked creation of singletons and unchecked use of static mut variables are huge red flags.

It's clean on this way, as explained in the unsafe section.

> Explicit panicking (e.g. unwrap) is used instead of proper error handling. However, note that unreachable! is OK if properly used.

There is quite a lot of`unwrap()`s, mainly on `heapless::Vec::push`, SPI calls and RTFM message passing.

### CODE REVIEW

**Comment by TeXitoi** [comment]
I can add a commit to remove the placeholders if needed.

**Comment by japaric** [comment]
Thanks for submitting! This is a cool project and the code is neatly organized: the
`portable` crate lets you test some logic on x86, which is great. This gets an
approval from me.

Some comments below:

> There is one unsafe to clear a timer interrupt (yes, I need to upstream that).

I think you can replace the `TIM3` task with a periodic soft task.

``` rust
#[init(spawn = [periodic])]
fn init() {
    spawn.periodic().expect("UNREACHABLE");
    // ..
}

const SYSCLK: u32 = 72_000_000; /* Hz */
const PERIOD: u32 = SYSCLK / 10_000;

#[task(schedule = [periodic])]
fn periodic() {
    schedule.periodic(PERIOD.cycles()).expect("UNREACHABLE");

    // ..
}
```

That would get rid of one `unsafe`.

> I don't understand what is support code

Support code is the code that's in the repository but not in the binary
(application) crate. The `portable` crate is your application support code.

> `unwrap`

I see it being used for roughly three different things:

- For IO errors, mainly SPI errors.

These *are* unrecoverable errors but IMO these should not result in panics but
instead should put the microcontroller in a "hardware failure" state. In this
state, for example, a red LED (or some other indicator) could be turned on and
the program execution would be halted (e.g. WFI).

The reason I would do this is that these errors can happen *if* there are
hardware errors (e.g. bad wiring) or software bugs (e.g. bad phase/polarity),
but otherwise should never occur during normal operation so the "hardware
failure" indicator can help you test during assembly / before deploy. If these
errors happen during normal operation the indicator would still mean "human
action required", which would be good to have around.

- `write!` / `Vec.push`

Here panicking is used to catch the bug (programmer error) of picking a buffer
that's too small. If the right size is used then hese panicking branches will be
unreachable at runtime and LLVM will likely optimize them away.

Panicking is certainly the right action here but I would refactor the code to
have less `unwrap`s. Also, for readability, the `unwrap`, or `expect`, should
include a comment stating the panicking reason, or you can write the reason in
the panic string.

``` rust
impl Thing {
    pub fn public(&self, ..) -> Vec<Cmd, U4> {
        self.impl_().expect("BUG: buffer is too small")
    }

    fn impl_(&self, ..) -> Option<Vec<Cmd, U4>> {
        let mut cmds = Vec::new();
        // ..
        cmd.push(..).ok()?;

        if cond {
            // ..
            cmd.push(..).ok()?;
        }

        cmd.push(..).ok()?;

        cmds
    }
}
```

- `spawn`

In most cases a `spawn` failure indicates a scheduling error, which is a
software bug. This error is unrecoverable and fixing the bug would likely
require restructuring the application, tweaking the priorities, tweaking clock
frequencies or something along those lines.

Panicking on a scheduling error is the right action (but you should fix all
those panics during development!). However, there may be a legitimate use case
for *ignoring* the error, though I can't think of any good example right now. I
was going to say "dropping network packets" (when you know the client will
retry) is a good example but you'll likely find out that you can't handle a new
packet *before* you call `spawn` (e.g. the memory pool you write packets into
becomes exhausted).

Some `spawn(..).unwrap()` obviously won't panic (e.g. the ones in `init`); I
would suggest adding "never panics because $REASON" comments to those (or
writing `.expect("UNREACHABLE")`). However, most `spawn`s will require WCET +
scheduling analysis to determine if they'll fail or not -- not much that you can do
for those today.

**Review by japaric — APPROVED** [review]

**Comment by TeXitoi** [comment]
@japaric Thanks for the feedback, will try to improve the code using your remarks.

For the `spawn` unwraps, it's in theory possible to overflow the message queue by pushing buttons faster that the task can manage. I think that's not possible because of the debouncing.

**Review by therealprof — APPROVED** [review]
Very nice!

**Review by jamesmunns — APPROVED** [review]

**Comment by mathk** [comment]
@japaric I guess we ca nmerge this oone with 3 approve ?

**Comment by TeXitoi** [comment]
Maybe I should remove the placeholders before merging?

**Comment by japaric** [comment]
@mathk the resources team has 8 members so we need a few more votes to reach 50%+1.

@TeXitoi adding a commit would clear the current approvals; let's do that in a follow-up PR

**Review by andre-richter — APPROVED** [review]
A worthy first project! :+1:

**Review by adamgreig — APPROVED** [review]
Looks good!

**Comment by japaric** [comment]
This has enough approvals (4/7 -- I'm no longer on the resources team) so let's merge this!

bors r+

**Pull request merged**
